name: Bug Report
description: Report a bug in SSL
labels: [\"C-bug\"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: input
    id: version
    attributes:
      label: SSL Version
      description: Output of \cargo run -- --version\
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Code to Reproduce
      description: Minimal SSL code that reproduces the issue
      placeholder: |
        fn main() {
            // Your code here
        }
      render: ssl
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (errors, crashes, wrong output)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: OS, Rust version, any other relevant info
